CREATE DATABASE printtracker;

CREATE TABLE users (
userID INT NOT NULL AUTO_INCREMENT,
warriorID INT UNIQUE NOT NULL,
firstName VARCHAR(50) NOT NULL,
lastName VARCHAR(100) NOT NULL,
isAdmin BOOL DEFAULT 0 NOT NULL,
adminPass VARCHAR(100),
PRIMARY KEY(userID)
)

CREATE TABLE prints(
printID INT NOT NULL AUTO_INCREMENT,
userID INT NOT NULL,
description VARCHAR(250) NOT NULL,
price DOUBLE(5,2) NOT NULL,
printDate DATE NOT NULL,
invoiced BOOL NOT NULL DEFAULT 0,
PRIMARY KEY(printID),
FOREIGN KEY (userID) REFERENCES users(userID)
)